import type { Calling, CallingId, City, ItemDef, Lineage, LineageId, MonsterDef, Recipe } from "./types";


export const SAVE_VERSION = 1;
export const SAVE_KEY = "veilborne-save-v1";
export const COMPANY = "Unrea1Merc Game Studios";
export const GAME_TITLE = "Veilborne";
export const GAME_TAG = "The Hidden Kingdoms";

export const CELL = 0.0024;
export const CITY_RADIUS_M = 9000;
export const TOWN_RADIUS_M = 2400;
export const HAMLET_RADIUS_M = 520;
export const INTERACT_M = 42;
export const SHARD_GOAL = 5;
export const START_LAT = 35.2271;
export const START_LNG = -80.8431;

export const STORY = [
  "The Elder Crown bound two worlds: the one you walk, and Aetherfell beneath it.",
  "When the Crown shattered, the Veil tore. Monsters hunt the same streets, parks, and hills as you.",
  "You are Veilborne — a walker who sees both layers. Raise a house. Join a guild. Gather five Crown shards.",
  "Restore the Crown. Or claim its pieces for yourself.",
];

export const LINEAGES: Lineage[] = [
  {
    id: "dawnfolk",
    name: "Dawnfolk",
    title: "of the walking cities",
    blurb: "Balanced heirs of the first mapped kingdoms. Steady sword-arm, steady will.",
    hp: 0,
    strength: 0,
    mana: 0,
  },
  {
    id: "highborn",
    name: "Highborn",
    title: "of the torn spires",
    blurb: "Tall-blooded scholars of the Veil. Thin-skinned, bright with mana.",
    hp: -8,
    strength: -1,
    mana: 14,
  },
  {
    id: "northkin",
    name: "Northkin",
    title: "of the frost marches",
    blurb: "Winter-hardened. They take a beating and keep walking.",
    hp: 16,
    strength: 1,
    mana: -6,
  },
  {
    id: "wildkin",
    name: "Wildkin",
    title: "of the green between",
    blurb: "Beast-blooded scouts. Strong of claw, impatient with walls.",
    hp: 4,
    strength: 3,
    mana: -4,
  },
];

export const CALLINGS: Calling[] = [
  {
    id: "blade",
    name: "Blade",
    blurb: "Steel first. You close the gap and end the hunt.",
    skill: "Sunder",
    skillBlurb: "A heavy cut that scales with strength.",
    manaCost: 8,
    weaponHint: "swords",
  },
  {
    id: "mystic",
    name: "Mystic",
    blurb: "You pull threads of the Veil and throw them as light.",
    skill: "Veil Bolt",
    skillBlurb: "A mana lance. Ignores a portion of armor.",
    manaCost: 12,
    weaponHint: "staves",
  },
  {
    id: "scout",
    name: "Scout",
    blurb: "Two shots, one breath. You never stand still.",
    skill: "Twin Shot",
    skillBlurb: "Two lighter hits; high chance to loot extra.",
    manaCost: 10,
    weaponHint: "bows",
  },
];

export const CLOAKS = [
  { name: "Sage", hue: 0 },
  { name: "Ash", hue: 40 },
  { name: "River", hue: 160 },
  { name: "Dusk", hue: 220 },
  { name: "Ember", hue: 320 },
  { name: "Bone", hue: 80 },
];

export const ITEMS: Record<string, ItemDef> = {
  "rusty-blade": {
    id: "rusty-blade",
    name: "Rusty Blade",
    kind: "weapon",
    slot: "weapon",
    rarity: "common",
    icon: "sword",
    atk: 4,
    desc: "A traveler's first mistake, still sharp enough.",
    value: 12,
  },
  "iron-sword": {
    id: "iron-sword",
    name: "Iron Sword",
    kind: "weapon",
    slot: "weapon",
    rarity: "uncommon",
    icon: "sword",
    atk: 9,
    desc: "Honest steel from a mapped town forge.",
    value: 48,
  },
  "veil-edge": {
    id: "veil-edge",
    name: "Veil Edge",
    kind: "weapon",
    slot: "weapon",
    rarity: "rare",
    icon: "sword",
    atk: 16,
    str: 2,
    desc: "The metal remembers both worlds.",
    value: 160,
  },
  "oak-staff": {
    id: "oak-staff",
    name: "Oak Staff",
    kind: "weapon",
    slot: "weapon",
    rarity: "common",
    icon: "staff",
    atk: 3,
    mana: 6,
    desc: "A walking stick that hums at dusk.",
    value: 14,
  },
  "crystal-staff": {
    id: "crystal-staff",
    name: "Crystal Staff",
    kind: "weapon",
    slot: "weapon",
    rarity: "rare",
    icon: "staff",
    atk: 11,
    mana: 14,
    desc: "A captured tear of the Veil.",
    value: 150,
  },
  "hunter-bow": {
    id: "hunter-bow",
    name: "Hunter Bow",
    kind: "weapon",
    slot: "weapon",
    rarity: "common",
    icon: "bow",
    atk: 5,
    desc: "Quiet, hungry, patient.",
    value: 16,
  },
  "rune-bow": {
    id: "rune-bow",
    name: "Rune Bow",
    kind: "weapon",
    slot: "weapon",
    rarity: "rare",
    icon: "bow",
    atk: 13,
    desc: "Each arrow writes a small law.",
    value: 155,
  },
  "cloth-wrap": {
    id: "cloth-wrap",
    name: "Cloth Wrap",
    kind: "armor",
    slot: "armor",
    rarity: "common",
    icon: "armor",
    def: 2,
    desc: "Better than skin.",
    value: 10,
  },
  "leather-jack": {
    id: "leather-jack",
    name: "Leather Jack",
    kind: "armor",
    slot: "armor",
    rarity: "uncommon",
    icon: "armor",
    def: 6,
    hp: 8,
    desc: "Boiled hide, stitched by a guild hand.",
    value: 54,
  },
  "chain-shirt": {
    id: "chain-shirt",
    name: "Chain Shirt",
    kind: "armor",
    slot: "armor",
    rarity: "rare",
    icon: "armor",
    def: 11,
    hp: 16,
    desc: "Rings that remember every blow.",
    value: 140,
  },
  "leather-helm": {
    id: "leather-helm",
    name: "Leather Helm",
    kind: "armor",
    slot: "helm",
    rarity: "common",
    icon: "helm",
    def: 2,
    desc: "Keeps the rain and the claws off.",
    value: 18,
  },
  "iron-helm": {
    id: "iron-helm",
    name: "Iron Helm",
    kind: "armor",
    slot: "helm",
    rarity: "uncommon",
    icon: "helm",
    def: 5,
    desc: "A mapped-town standard.",
    value: 44,
  },
  "trail-boots": {
    id: "trail-boots",
    name: "Trail Boots",
    kind: "armor",
    slot: "boots",
    rarity: "common",
    icon: "boots",
    def: 1,
    desc: "Miles already in the soles.",
    value: 14,
  },
  "guard-shield": {
    id: "guard-shield",
    name: "Guard Shield",
    kind: "armor",
    slot: "accessory",
    rarity: "uncommon",
    icon: "shield",
    def: 4,
    desc: "A city crest, filed off.",
    value: 40,
  },
  "health-draught": {
    id: "health-draught",
    name: "Health Draught",
    kind: "consumable",
    rarity: "common",
    icon: "potion-hp",
    desc: "Restores a stout measure of health.",
    value: 28,
  },
  "mana-draught": {
    id: "mana-draught",
    name: "Mana Draught",
    kind: "consumable",
    rarity: "common",
    icon: "potion-mp",
    desc: "Clears the static from your Veil-sight.",
    value: 28,
  },
  "quick-revive": {
    id: "quick-revive",
    name: "Quick Revive",
    kind: "consumable",
    rarity: "rare",
    icon: "revive",
    desc: "Rise where you fell. No walk back to town.",
    value: 120,
  },
  herb: {
    id: "herb",
    name: "Veil Herb",
    kind: "material",
    rarity: "common",
    icon: "herb",
    desc: "Bitter green that grows on torn ground.",
    value: 4,
  },
  ore: {
    id: "ore",
    name: "Iron Ore",
    kind: "material",
    rarity: "common",
    icon: "ore",
    desc: "Heavy, honest, useful.",
    value: 6,
  },
  pelt: {
    id: "pelt",
    name: "Beast Pelt",
    kind: "material",
    rarity: "common",
    icon: "pelt",
    desc: "Still warm if you were quick.",
    value: 7,
  },
  bone: {
    id: "bone",
    name: "Old Bone",
    kind: "material",
    rarity: "common",
    icon: "bone",
    desc: "Something walked these streets before you.",
    value: 5,
  },
  shard: {
    id: "shard",
    name: "Crown Shard",
    kind: "quest",
    rarity: "relic",
    icon: "coin",
    desc: "A fragment of the Elder Crown. Five make a throne.",
    value: 0,
  },
};

export const RECIPES: Recipe[] = [
  {
    id: "brew-hp",
    name: "Brew Health Draught",
    out: { id: "health-draught", qty: 1 },
    ins: [
      { id: "herb", qty: 2 },
      { id: "bone", qty: 1 },
    ],
    station: "camp",
  },
  {
    id: "brew-mp",
    name: "Brew Mana Draught",
    out: { id: "mana-draught", qty: 1 },
    ins: [
      { id: "herb", qty: 2 },
      { id: "ore", qty: 1 },
    ],
    station: "camp",
  },
  {
    id: "forge-sword",
    name: "Forge Iron Sword",
    out: { id: "iron-sword", qty: 1 },
    ins: [
      { id: "ore", qty: 3 },
      { id: "bone", qty: 1 },
    ],
    station: "house",
  },
  {
    id: "stitch-jack",
    name: "Stitch Leather Jack",
    out: { id: "leather-jack", qty: 1 },
    ins: [
      { id: "pelt", qty: 3 },
      { id: "herb", qty: 1 },
    ],
    station: "house",
  },
  {
    id: "forge-helm",
    name: "Forge Iron Helm",
    out: { id: "iron-helm", qty: 1 },
    ins: [
      { id: "ore", qty: 2 },
      { id: "pelt", qty: 1 },
    ],
    station: "house",
  },
  {
    id: "guild-chain",
    name: "Guild Chain Shirt",
    out: { id: "chain-shirt", qty: 1 },
    ins: [
      { id: "ore", qty: 4 },
      { id: "pelt", qty: 2 },
    ],
    station: "guild",
  },
  {
    id: "guild-edge",
    name: "Temper Veil Edge",
    out: { id: "veil-edge", qty: 1 },
    ins: [
      { id: "iron-sword", qty: 1 },
      { id: "ore", qty: 3 },
      { id: "herb", qty: 2 },
    ],
    station: "guild",
  },
  {
    id: "phoenix",
    name: "Bind a Quick Revive",
    out: { id: "quick-revive", qty: 1 },
    ins: [
      { id: "herb", qty: 4 },
      { id: "bone", qty: 2 },
      { id: "pelt", qty: 1 },
    ],
    station: "house",
  },
];

export const MONSTERS: Record<string, MonsterDef> = {
  slime: {
    id: "slime",
    name: "Mire Slime",
    hp: 22,
    atk: 5,
    xp: 12,
    gold: 6,
    sprite: "/sprites/monsters/slime.png",
    loot: [{ id: "herb", chance: 0.7, qty: [1, 2] }],
    tags: ["wild"],
  },
  goblin: {
    id: "goblin",
    name: "Hedge Goblin",
    hp: 28,
    atk: 7,
    xp: 18,
    gold: 10,
    sprite: "/sprites/monsters/goblin.png",
    loot: [
      { id: "bone", chance: 0.5, qty: [1, 1] },
      { id: "herb", chance: 0.4, qty: [1, 2] },
    ],
    tags: ["wild", "city"],
  },
  wolf: {
    id: "wolf",
    name: "Park Wolf",
    hp: 34,
    atk: 9,
    xp: 22,
    gold: 8,
    sprite: "/sprites/monsters/wolf.png",
    loot: [{ id: "pelt", chance: 0.75, qty: [1, 2] }],
    tags: ["wild"],
  },
  spider: {
    id: "spider",
    name: "Cave Spider",
    hp: 30,
    atk: 10,
    xp: 24,
    gold: 9,
    sprite: "/sprites/monsters/spider.png",
    loot: [
      { id: "herb", chance: 0.4, qty: [1, 1] },
      { id: "bone", chance: 0.3, qty: [1, 1] },
    ],
    tags: ["cave"],
  },
  skeleton: {
    id: "skeleton",
    name: "Street Wight",
    hp: 38,
    atk: 11,
    xp: 28,
    gold: 14,
    sprite: "/sprites/monsters/skeleton.png",
    loot: [
      { id: "bone", chance: 0.9, qty: [1, 3] },
      { id: "rusty-blade", chance: 0.12, qty: [1, 1] },
    ],
    tags: ["night", "cave"],
  },
  imp: {
    id: "imp",
    name: "Alley Imp",
    hp: 24,
    atk: 8,
    xp: 16,
    gold: 12,
    sprite: "/sprites/monsters/imp.png",
    loot: [
      { id: "ore", chance: 0.35, qty: [1, 1] },
      { id: "herb", chance: 0.4, qty: [1, 1] },
    ],
    tags: ["city", "night"],
  },
  orc: {
    id: "orc",
    name: "Ash Orc",
    hp: 52,
    atk: 13,
    xp: 40,
    gold: 22,
    sprite: "/sprites/monsters/orc.png",
    loot: [
      { id: "ore", chance: 0.6, qty: [1, 3] },
      { id: "pelt", chance: 0.4, qty: [1, 1] },
    ],
    tags: ["wild", "cave"],
  },
  wraith: {
    id: "wraith",
    name: "Veil Wraith",
    hp: 44,
    atk: 14,
    xp: 36,
    gold: 18,
    sprite: "/sprites/monsters/wraith.png",
    loot: [
      { id: "herb", chance: 0.5, qty: [1, 2] },
      { id: "mana-draught", chance: 0.2, qty: [1, 1] },
    ],
    tags: ["night", "cave"],
  },
  troll: {
    id: "troll",
    name: "Underpass Troll",
    hp: 70,
    atk: 16,
    xp: 55,
    gold: 32,
    sprite: "/sprites/monsters/troll.png",
    loot: [
      { id: "ore", chance: 0.8, qty: [2, 4] },
      { id: "leather-helm", chance: 0.15, qty: [1, 1] },
    ],
    tags: ["cave", "boss"],
  },
  dragon: {
    id: "dragon",
    name: "Shard Wyrm",
    hp: 96,
    atk: 18,
    xp: 90,
    gold: 60,
    sprite: "/sprites/monsters/dragon.png",
    loot: [
      { id: "ore", chance: 1, qty: [2, 5] },
      { id: "veil-edge", chance: 0.08, qty: [1, 1] },
    ],
    tags: ["boss", "cave"],
  },
};

export const CITIES: City[] = [
  { id: "charlotte", name: "Charlotte", lat: 35.2271, lng: -80.8431, size: "city" },
  { id: "concord", name: "Concord", lat: 35.4088, lng: -80.5795, size: "town" },
  { id: "gastonia", name: "Gastonia", lat: 35.2621, lng: -81.1873, size: "town" },
  { id: "rockhill", name: "Rock Hill", lat: 34.9249, lng: -81.0251, size: "town" },
  { id: "matthews", name: "Matthews", lat: 35.1168, lng: -80.7237, size: "town" },
  { id: "huntersville", name: "Huntersville", lat: 35.4107, lng: -80.8428, size: "town" },
  { id: "kannapolis", name: "Kannapolis", lat: 35.4874, lng: -80.6217, size: "town" },
  { id: "monroe-nc", name: "Monroe", lat: 34.9854, lng: -80.5495, size: "town" },
  { id: "indian-trail", name: "Indian Trail", lat: 35.0768, lng: -80.6692, size: "town" },
  { id: "mint-hill", name: "Mint Hill", lat: 35.1799, lng: -80.6473, size: "town" },
  { id: "cornelius", name: "Cornelius", lat: 35.4868, lng: -80.8601, size: "town" },
  { id: "davidson", name: "Davidson", lat: 35.4993, lng: -80.8487, size: "town" },
  { id: "fort-mill", name: "Fort Mill", lat: 35.0074, lng: -80.9451, size: "town" },
  { id: "pineville", name: "Pineville", lat: 35.0832, lng: -80.8884, size: "town" },
  { id: "belmont-nc", name: "Belmont", lat: 35.2429, lng: -81.0373, size: "town" },
  { id: "salisbury", name: "Salisbury", lat: 35.671, lng: -80.4742, size: "town" },
  { id: "statesville", name: "Statesville", lat: 35.7826, lng: -80.8873, size: "town" },
  { id: "hickory", name: "Hickory", lat: 35.7345, lng: -81.3445, size: "town" },
  { id: "asheville", name: "Asheville", lat: 35.5951, lng: -82.5515, size: "city" },
  { id: "raleigh", name: "Raleigh", lat: 35.7796, lng: -78.6382, size: "city" },
  { id: "durham", name: "Durham", lat: 35.994, lng: -78.8986, size: "city" },
  { id: "greensboro", name: "Greensboro", lat: 36.0726, lng: -79.792, size: "city" },
  { id: "winston", name: "Winston-Salem", lat: 36.0999, lng: -80.2442, size: "city" },
  { id: "wilmington-nc", name: "Wilmington", lat: 34.2257, lng: -77.9447, size: "city" },
  { id: "fayetteville", name: "Fayetteville", lat: 35.0527, lng: -78.8784, size: "city" },
  { id: "charleston", name: "Charleston", lat: 32.7765, lng: -79.9311, size: "city" },
  { id: "columbia-sc", name: "Columbia", lat: 34.0007, lng: -81.0348, size: "city" },
  { id: "greenville-sc", name: "Greenville", lat: 34.8526, lng: -82.394, size: "city" },
  { id: "anderson-sc", name: "Anderson", lat: 34.5034, lng: -82.6501, size: "town" },
  { id: "belton-sc", name: "Belton", lat: 34.5229, lng: -82.4943, size: "town" },
  { id: "honea-path", name: "Honea Path", lat: 34.4468, lng: -82.3915, size: "town" },
  { id: "williamston-sc", name: "Williamston", lat: 34.6184, lng: -82.4779, size: "town" },
  { id: "easley", name: "Easley", lat: 34.8298, lng: -82.6015, size: "town" },
  { id: "simpsonville", name: "Simpsonville", lat: 34.7371, lng: -82.2543, size: "town" },
  { id: "mauldin", name: "Mauldin", lat: 34.7787, lng: -82.3101, size: "town" },
  { id: "greer", name: "Greer", lat: 34.9387, lng: -82.2271, size: "town" },
  { id: "spartanburg", name: "Spartanburg", lat: 34.9496, lng: -81.932, size: "city" },
  { id: "clemson", name: "Clemson", lat: 34.6834, lng: -82.8374, size: "town" },
  { id: "seneca-sc", name: "Seneca", lat: 34.6859, lng: -82.9532, size: "town" },
  { id: "greenwood-sc", name: "Greenwood", lat: 34.1954, lng: -82.1618, size: "town" },
  { id: "pendleton-sc", name: "Pendleton", lat: 34.6518, lng: -82.7838, size: "town" },
  { id: "liberty-sc", name: "Liberty", lat: 34.7882, lng: -82.6924, size: "town" },
  { id: "gaffney", name: "Gaffney", lat: 35.0718, lng: -81.6498, size: "town" },
  { id: "nyc", name: "New York", lat: 40.7128, lng: -74.006, size: "city" },
  { id: "la", name: "Los Angeles", lat: 34.0522, lng: -118.2437, size: "city" },
  { id: "chicago", name: "Chicago", lat: 41.8781, lng: -87.6298, size: "city" },
  { id: "miami", name: "Miami", lat: 25.7617, lng: -80.1918, size: "city" },
  { id: "seattle", name: "Seattle", lat: 47.6062, lng: -122.3321, size: "city" },
  { id: "denver", name: "Denver", lat: 39.7392, lng: -104.9903, size: "city" },
  { id: "austin", name: "Austin", lat: 30.2672, lng: -97.7431, size: "city" },
  { id: "houston", name: "Houston", lat: 29.7604, lng: -95.3698, size: "city" },
  { id: "dallas", name: "Dallas", lat: 32.7767, lng: -96.797, size: "city" },
  { id: "sf", name: "San Francisco", lat: 37.7749, lng: -122.4194, size: "city" },
  { id: "san-diego", name: "San Diego", lat: 32.7157, lng: -117.1611, size: "city" },
  { id: "phoenix", name: "Phoenix", lat: 33.4484, lng: -112.074, size: "city" },
  { id: "boston", name: "Boston", lat: 42.3601, lng: -71.0589, size: "city" },
  { id: "atlanta", name: "Atlanta", lat: 33.749, lng: -84.388, size: "city" },
  { id: "philadelphia", name: "Philadelphia", lat: 39.9526, lng: -75.1652, size: "city" },
  { id: "dc", name: "Washington", lat: 38.9072, lng: -77.0369, size: "city" },
  { id: "nashville", name: "Nashville", lat: 36.1627, lng: -86.7816, size: "city" },
  { id: "portland", name: "Portland", lat: 45.5152, lng: -122.6784, size: "city" },
  { id: "minneapolis", name: "Minneapolis", lat: 44.9778, lng: -93.265, size: "city" },
  { id: "detroit", name: "Detroit", lat: 42.3314, lng: -83.0458, size: "city" },
  { id: "orlando", name: "Orlando", lat: 28.5383, lng: -81.3792, size: "city" },
  { id: "tampa", name: "Tampa", lat: 27.9506, lng: -82.4572, size: "city" },
  { id: "new-orleans", name: "New Orleans", lat: 29.9511, lng: -90.0715, size: "city" },
  { id: "vegas", name: "Las Vegas", lat: 36.1699, lng: -115.1398, size: "city" },
  { id: "salt-lake", name: "Salt Lake City", lat: 40.7608, lng: -111.891, size: "city" },
  { id: "kansas-city", name: "Kansas City", lat: 39.0997, lng: -94.5786, size: "city" },
  { id: "st-louis", name: "St. Louis", lat: 38.627, lng: -90.1994, size: "city" },
  { id: "indianapolis", name: "Indianapolis", lat: 39.7684, lng: -86.1581, size: "city" },
  { id: "columbus-oh", name: "Columbus", lat: 39.9612, lng: -82.9988, size: "city" },
  { id: "pittsburgh", name: "Pittsburgh", lat: 40.4406, lng: -79.9959, size: "city" },
  { id: "cleveland", name: "Cleveland", lat: 41.4993, lng: -81.6944, size: "city" },
  { id: "cincinnati", name: "Cincinnati", lat: 39.1031, lng: -84.512, size: "city" },
  { id: "milwaukee", name: "Milwaukee", lat: 43.0389, lng: -87.9065, size: "city" },
  { id: "richmond", name: "Richmond", lat: 37.5407, lng: -77.436, size: "city" },
  { id: "louisville", name: "Louisville", lat: 38.2527, lng: -85.7585, size: "city" },
  { id: "oklahoma-city", name: "Oklahoma City", lat: 35.4676, lng: -97.5164, size: "city" },
  { id: "albuquerque", name: "Albuquerque", lat: 35.0844, lng: -106.6504, size: "city" },
  { id: "tucson", name: "Tucson", lat: 32.2226, lng: -110.9747, size: "city" },
  { id: "sacramento", name: "Sacramento", lat: 38.5816, lng: -121.4944, size: "city" },
  { id: "san-jose", name: "San Jose", lat: 37.3382, lng: -121.8863, size: "city" },
  { id: "oakland", name: "Oakland", lat: 37.8044, lng: -122.2712, size: "city" },
  { id: "honolulu", name: "Honolulu", lat: 21.3069, lng: -157.8583, size: "city" },
  { id: "anchorage", name: "Anchorage", lat: 61.2181, lng: -149.9003, size: "city" },
  { id: "baltimore", name: "Baltimore", lat: 39.2904, lng: -76.6122, size: "city" },
  { id: "london", name: "London", lat: 51.5074, lng: -0.1278, size: "city" },
  { id: "paris", name: "Paris", lat: 48.8566, lng: 2.3522, size: "city" },
  { id: "berlin", name: "Berlin", lat: 52.52, lng: 13.405, size: "city" },
  { id: "rome", name: "Rome", lat: 41.9028, lng: 12.4964, size: "city" },
  { id: "madrid", name: "Madrid", lat: 40.4168, lng: -3.7038, size: "city" },
  { id: "tokyo", name: "Tokyo", lat: 35.6762, lng: 139.6503, size: "city" },
  { id: "seoul", name: "Seoul", lat: 37.5665, lng: 126.978, size: "city" },
  { id: "sydney", name: "Sydney", lat: -33.8688, lng: 151.2093, size: "city" },
  { id: "toronto", name: "Toronto", lat: 43.6532, lng: -79.3832, size: "city" },
  { id: "mexico", name: "Mexico City", lat: 19.4326, lng: -99.1332, size: "city" },
  { id: "sao", name: "São Paulo", lat: -23.5505, lng: -46.6333, size: "city" },
  { id: "cairo", name: "Cairo", lat: 30.0444, lng: 31.2357, size: "city" },
  { id: "nairobi", name: "Nairobi", lat: -1.2921, lng: 36.8219, size: "city" },
  { id: "mumbai", name: "Mumbai", lat: 19.076, lng: 72.8777, size: "city" },
  { id: "singapore", name: "Singapore", lat: 1.3521, lng: 103.8198, size: "city" },
  { id: "auckland", name: "Auckland", lat: -36.8509, lng: 174.7645, size: "city" },
  { id: "vancouver", name: "Vancouver", lat: 49.2827, lng: -123.1207, size: "city" },
  { id: "dublin", name: "Dublin", lat: 53.3498, lng: -6.2603, size: "city" },
  { id: "oslo", name: "Oslo", lat: 59.9139, lng: 10.7522, size: "city" },
];

export const HAMLET_NAMES = [
  "Oakford",
  "Millhaven",
  "Thornwick",
  "Redhollow",
  "Ashmere",
  "Crowfield",
  "Pinecross",
  "Goldwell",
  "Fairbarrow",
  "Nettleby",
  "Stoneford",
  "Elmstead",
  "Brookhaven",
  "Greyfen",
  "Larkspur",
  "Mossbank",
  "Hartfield",
  "Willowmere",
  "Brightford",
  "Ravenhill",
  "Cinderwell",
  "Fogbarrow",
  "Heatherford",
  "Ivywatch",
  "Juniper Bend",
  "Kestrel Gate",
  "Lowmarsh",
  "Marrowby",
  "Northwell",
  "Oatcroft",
  "Pewterbridge",
  "Quillwick",
  "Rushmead",
  "Silverfen",
  "Tallowby",
  "Umberford",
];

export const WANDER_NAMES = [
  "Sera Vale",
  "Brann Oak",
  "Lysa Thorn",
  "Calder Rune",
  "Mirin Ash",
  "Tov Ember",
  "Neris Holt",
  "Jace Quill",
  "Orla Finn",
  "Perrin Shade",
  "Kest Rowan",
  "Auden Vale",
];

export function npcIdFromName(name: string) {
  return `npc:${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`;
}

export const STORE_OFFERS: Array<{
  id: string;
  itemId?: string;
  name: string;
  desc: string;
  gold: number;
  veilmarks?: number;
  icon: string;
  kind: "item" | "revive" | "restock";
}> = [
  {
    id: "buy-hp",
    itemId: "health-draught",
    name: "Health Draught",
    desc: "Sip in the field. Stand back up.",
    gold: 35,
    icon: "potion-hp",
    kind: "item",
  },
  {
    id: "buy-mp",
    itemId: "mana-draught",
    name: "Mana Draught",
    desc: "For the bolt you cannot afford to miss.",
    gold: 35,
    icon: "potion-mp",
    kind: "item",
  },
  {
    id: "buy-hp5",
    itemId: "health-draught",
    name: "Five Draughts",
    desc: "A traveler's bundle.",
    gold: 150,
    icon: "potion-hp",
    kind: "item",
  },
  {
    id: "buy-revive",
    name: "Quick Revive",
    desc: "Do not walk back to town. Rise here.",
    gold: 140,
    veilmarks: 3,
    icon: "revive",
    kind: "revive",
  },
  {
    id: "buy-sword",
    itemId: "iron-sword",
    name: "Iron Sword",
    desc: "Town steel. Reliable.",
    gold: 70,
    icon: "sword",
    kind: "item",
  },
  {
    id: "buy-staff",
    itemId: "oak-staff",
    name: "Oak Staff",
    desc: "A mystic's first true tool.",
    gold: 55,
    icon: "staff",
    kind: "item",
  },
  {
    id: "buy-bow",
    itemId: "hunter-bow",
    name: "Hunter Bow",
    desc: "For those who keep their distance.",
    gold: 58,
    icon: "bow",
    kind: "item",
  },
  {
    id: "buy-jack",
    itemId: "leather-jack",
    name: "Leather Jack",
    desc: "A little less death.",
    gold: 80,
    icon: "armor",
    kind: "item",
  },
];

export function xpToNext(level: number) {
  return Math.floor(36 * Math.pow(level, 1.55));
}

export function baseStats(lineage: LineageId, calling: CallingId) {
  const l = LINEAGES.find((x) => x.id === lineage)!;
  const extraHp = calling === "blade" ? 8 : calling === "scout" ? 4 : 0;
  const extraStr = calling === "blade" ? 2 : calling === "scout" ? 1 : 0;
  const extraMn = calling === "mystic" ? 10 : calling === "scout" ? 4 : 0;
  return {
    maxHp: 48 + l.hp + extraHp,
    strength: 6 + l.strength + extraStr,
    maxMana: 22 + l.mana + extraMn,
  };
}

export function starterWeapon(calling: CallingId) {
  if (calling === "mystic") return "oak-staff";
  if (calling === "scout") return "hunter-bow";
  return "rusty-blade";
}

export function iconSrc(icon: string) {
  return `/sprites/icons/${icon}.png`;
}
